baseURL = "https://www.duma.website/"
languageCode = "en-us"
title = "Duma's website"
theme = ["duma_template"]
paginate = 5
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'base16-snazzy'
    tabWidth = 4