name = "duma_template"
license = "MIT"
licenselink = "https://github.com/vimux/blank/blob/master/LICENSE"
description = "The template for my website"
homepage = "https://dumaron.github.io"

[author]
  name = "Duma"
  homepage = "https://dumaron.github.io"
